# Generated by Django 5.0 on 2024-01-05 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("RememberApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Details",
            new_name="Detail",
        ),
    ]
