# Generated by Django 5.0 on 2024-01-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RememberApp", "0002_rename_details_detail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.IntegerField()),
                ("massage", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="detail",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="detail",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="Payment_img",
            field=models.ImageField(upload_to="Payment_img/"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="mode_of_payment",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="payment_receiver",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="transaction_id",
            field=models.CharField(max_length=100),
        ),
    ]
